name: "Tests"

on: [pull_request]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - run: git checkout HEAD^2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: fetch-dev
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Start Server
        run: |
          docker compose up -d
          sleep 5

      - name: Run Tests
        run: docker compose exec -T php vendor/bin/phpunit --configuration phpunit.xml
